# .prettierrc.yaml
arrowParens: "always"
bracketSpacing: true
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
insertPragma: false
requirePragma: false
jsxBracketSameLine: false
jsxSingleQuote: false
printWidth: 80
proseWrap: "preserve"
quoteProps: "as-needed"
semi: true
singleQuote: false
tabWidth: 2
trailingComma: "es5"
useTabs: false
vueIndentScriptAndStyle: true
